# Generated by Django 5.2.11 on 2026-03-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='activity_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='activity_feedback_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='activity_feedback_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='activity_last_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='activity_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('correct', 'Correct'), ('incorrect', 'Incorrect')], default='pending', max_length=20),
        ),
    ]
