# Generated by Django 5.2.11 on 2026-03-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='activity_validation_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
