# Generated by hand for the PLMS admin panel feature.

from django.db import migrations, models


def populate_course_categories(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    for course in Course.objects.all():
        title = (course.title or "").lower()
        slug = (course.slug or "").lower()
        if "c#" in title or "csharp" in slug:
            category = "csharp"
        elif "python" in title or "python" in slug:
            category = "python"
        elif "php" in title or "php" in slug:
            category = "php"
        else:
            category = "general"
        Course.objects.filter(pk=course.pk).update(category=category)


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_lesson_activity_validation_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("csharp", "C#"),
                    ("python", "Python"),
                    ("php", "PHP"),
                    ("general", "General Programming"),
                ],
                default="general",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="lesson_images/"),
        ),
        migrations.CreateModel(
            name="LearningMaterial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="lesson_materials/")),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("image", "Image"),
                            ("archive", "Archive"),
                            ("other", "Other"),
                        ],
                        default="document",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="materials",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson__course", "lesson__order", "title"],
            },
        ),
        migrations.RunPython(populate_course_categories, migrations.RunPython.noop),
    ]
