# Generated by Django 5.2.11 on 2026-03-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_category_lesson_image_learningmaterial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningmaterial',
            options={'ordering': ['lesson__course', 'lesson__order', 'order', 'title']},
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='presentation_provider',
            field=models.CharField(choices=[('none', 'Not a presentation'), ('upload', 'Uploaded deck'), ('google_slides', 'Google Slides'), ('canva', 'Canva'), ('embed', 'Direct embed link')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='source_type',
            field=models.CharField(choices=[('file', 'Uploaded file'), ('url', 'External link')], default='file', max_length=12),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_materials/'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='material_type',
            field=models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('archive', 'Archive'), ('presentation', 'Presentation'), ('other', 'Other')], default='document', max_length=20),
        ),
    ]
