# Generated by Django 5.2.11 on 2026-03-24 01:57

from django.db import migrations, models


def populate_general_topics(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    defaults = {
        "csharp": "C# programming fundamentals",
        "python": "Python programming fundamentals",
        "php": "PHP programming fundamentals",
        "general": "General programming foundations",
    }

    for course in Course.objects.all():
        if (course.general_topic or "").strip():
            continue

        title = (course.title or "").strip().lower()
        if "c#" in title or "csharp" in title:
            topic = defaults["csharp"]
        elif "python" in title:
            topic = defaults["python"]
        elif "php" in title:
            topic = defaults["php"]
        else:
            topic = defaults.get(course.category or "general", defaults["general"])

        Course.objects.filter(pk=course.pk).update(general_topic=topic)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_learningmaterial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='general_topic',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(populate_general_topics, migrations.RunPython.noop),
    ]
