# Generated by Django 5.2.11 on 2026-03-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_general_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='general_topic',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('csharp', 'C# and .NET Development'), ('python', 'Python Programming and Automation'), ('php', 'PHP Web Development'), ('general', 'General Programming Foundations')], default='general', max_length=30),
        ),
    ]
