# Generated by Django 5.2.11 on 2026-03-17 04:00

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def build_unique_slug(Badge, value, *, pk=None):
    base_slug = slugify(value)[:200] or "badge"
    candidate = base_slug
    counter = 2
    queryset = Badge.objects.exclude(pk=pk)
    while queryset.filter(slug=candidate).exists():
        suffix = f"-{counter}"
        candidate = f"{base_slug[: max(1, 200 - len(suffix))]}{suffix}"
        counter += 1
    return candidate


def upsert_badge(Badge, course, award_type, name, description):
    badge = Badge.objects.filter(course_id=course.id, award_type=award_type).first()
    slug = build_unique_slug(Badge, name, pk=getattr(badge, "pk", None))
    if badge is None:
        badge = Badge.objects.create(
            course_id=course.id,
            award_type=award_type,
            name=name,
            slug=slug,
            description=description,
            is_active=True,
        )
        return badge

    badge.name = name
    badge.slug = slug
    badge.description = description
    badge.is_active = True
    badge.save(update_fields=["name", "slug", "description", "is_active"])
    return badge


def sync_badge_milestones(apps, schema_editor):
    Badge = apps.get_model("badges", "Badge")
    UserBadge = apps.get_model("badges", "UserBadge")
    Course = apps.get_model("courses", "Course")
    Enrollment = apps.get_model("courses", "Enrollment")

    badge_ids = {}
    for course in Course.objects.all():
        enrollment_badge = upsert_badge(
            Badge,
            course,
            "enrollment",
            f"{course.title} - Enrollment Badge",
            f"Awarded when you enroll in {course.title} and begin your guided path.",
        )
        completion_badge = upsert_badge(
            Badge,
            course,
            "completion",
            f"{course.title} - Completion Badge",
            f"Awarded after you finish every lesson and pass the final quiz in {course.title}.",
        )
        badge_ids[(course.id, "enrollment")] = enrollment_badge.id
        badge_ids[(course.id, "completion")] = completion_badge.id

    for enrollment in Enrollment.objects.all():
        enrollment_badge_id = badge_ids.get((enrollment.course_id, "enrollment"))
        if enrollment_badge_id:
            UserBadge.objects.get_or_create(
                user_id=enrollment.user_id,
                badge_id=enrollment_badge_id,
                defaults={
                    "course_id": enrollment.course_id,
                    "is_seen": True,
                },
            )

        if enrollment.completed_at:
            completion_badge_id = badge_ids.get((enrollment.course_id, "completion"))
            if completion_badge_id:
                UserBadge.objects.get_or_create(
                    user_id=enrollment.user_id,
                    badge_id=completion_badge_id,
                    defaults={
                        "course_id": enrollment.course_id,
                        "is_seen": True,
                    },
                )


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_lesson_activity_validation_rules"),
        ("badges", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badges",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="award_type",
            field=models.CharField(
                choices=[("enrollment", "Enrollment"), ("completion", "Completion")],
                default="completion",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userbadge",
            name="is_seen",
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name="badge",
            constraint=models.UniqueConstraint(
                condition=models.Q(course__isnull=False),
                fields=("course", "award_type"),
                name="unique_badge_per_course_and_type",
            ),
        ),
        migrations.RunPython(sync_badge_milestones, migrations.RunPython.noop),
    ]
