# Generated by Django 5.2.11 on 2026-03-17 05:15

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


PLATFORM_BADGES = [
    (
        "milestone:first-steps",
        "First Steps",
        "Enroll in your first course and open your achievement journey.",
        60,
    ),
    (
        "milestone:course-collector",
        "Course Collector",
        "Enroll in all available programming tracks and build a full learning lineup.",
        120,
    ),
    (
        "milestone:lesson-spark",
        "Lesson Spark",
        "Complete 6 lessons to show consistent momentum across the platform.",
        90,
    ),
    (
        "milestone:quiz-striker",
        "Quiz Striker",
        "Pass 3 quizzes and prove your learning is sticking.",
        100,
    ),
    (
        "milestone:perfect-pulse",
        "Perfect Pulse",
        "Hit a 100% score on any quiz to unlock this precision badge.",
        110,
    ),
    (
        "milestone:graduation-glow",
        "Graduation Glow",
        "Complete your first course and step into the next level as a finisher.",
        150,
    ),
    (
        "milestone:triple-crown",
        "Triple Crown",
        "Complete all three programming courses and become a full-path finisher.",
        260,
    ),
]


def build_unique_slug(Badge, value, *, pk=None):
    base_slug = slugify(value)[:200] or "badge"
    candidate = base_slug
    counter = 2
    queryset = Badge.objects.exclude(pk=pk)
    while queryset.filter(slug=candidate).exists():
        suffix = f"-{counter}"
        candidate = f"{base_slug[: max(1, 200 - len(suffix))]}{suffix}"
        counter += 1
    return candidate


def sync_badge_progression(apps, schema_editor):
    Badge = apps.get_model("badges", "Badge")

    for badge in Badge.objects.filter(course__isnull=False).select_related("course"):
        badge.criteria_key = f"course:{badge.course.slug}:{badge.award_type}"
        badge.xp_reward = 120 if badge.award_type == "completion" else 40
        if not badge.slug:
            badge.slug = build_unique_slug(Badge, badge.name, pk=badge.pk)
        badge.save(update_fields=["criteria_key", "xp_reward", "slug"])

    for criteria_key, name, description, xp_reward in PLATFORM_BADGES:
        badge = Badge.objects.filter(criteria_key=criteria_key).first()
        if badge is None:
            Badge.objects.create(
                criteria_key=criteria_key,
                name=name,
                slug=build_unique_slug(Badge, name),
                description=description,
                award_type="milestone",
                xp_reward=xp_reward,
                is_active=True,
            )
            continue

        badge.name = name
        badge.description = description
        badge.award_type = "milestone"
        badge.xp_reward = xp_reward
        badge.save(update_fields=["name", "description", "award_type", "xp_reward"])


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0004_badge_milestones"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="criteria_key",
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="badge",
            name="xp_reward",
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name="badge",
            name="award_type",
            field=models.CharField(
                choices=[
                    ("enrollment", "Enrollment"),
                    ("completion", "Completion"),
                    ("milestone", "Milestone"),
                ],
                default="completion",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userbadge",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badge_awards",
                to="courses.course",
            ),
        ),
        migrations.RunPython(sync_badge_progression, migrations.RunPython.noop),
    ]
